name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: git pull, build and deploy
      run: |
        sshpass -p ${{ secrets.pw }} ssh root@95.216.160.112 -o StrictHostKeyChecking=no < ./deploy-backend.bash
